### ISSUE TITLE
A few color issues

### ISSUE THREAD

**Issue by carlocaione** [Tsuzat/NeoSolarized.nvim#17] opened 2024-02-03 19:40 UTC
Using `neo-tree` I have a few lines that are not readable (see the line under `cmd.txt` in dark gray) and the line highlight is not visible at all (`Cargo.toml` should be highlighted).

<img width="279" alt="Screenshot 2024-02-03 at 20 34 50" src="https://github.com/Tsuzat/NeoSolarized.nvim/assets/357758/1c9efb28-acc8-494b-8249-a5f722b1f4b6">

Using `fidget` the background is black:

<img width="279" alt="Screenshot 2024-02-03 at 20 38 06" src="https://github.com/Tsuzat/NeoSolarized.nvim/assets/357758/b06c3efe-8c1e-4c62-a36b-ab6e99db3e20">

**Comment by Tsuzat** [comment] 2024-02-08 08:36
Hi @carlocaione, I personally do not use `NeoTree`. All the highlight groups of `NeoTree` are written with reference of `NvimTree` (which I use personally). I would suggest you to try going thought [these lines of code](https://github.com/Tsuzat/NeoSolarized.nvim/blob/687c780ff11253b474f9a777482648f8f4c39185/lua/NeoSolarized/theme.lua#L377). Please try to improve the highlight groups. Pull requests are welcomed and appreciated. 

You can also change the hightlight groups from the config itself by using following line inside setup
```lua
-- Add specific hightlight groups
  on_highlights = function(highlights, colors) 
    -- highlights.Include.fg = colors.red -- Using `red` foreground for Includes
  end, 
```

**Comment by carlocaione** [comment] 2024-02-08 08:54
@Tsuzat I'll try to look into the `NeoTree` stuff but the problem with the line highlight is more generic I think. Do you get the current line highlighted when you give `:set cursorline`? Trying to understand whether this is an issue with my setup.

**Comment by Tsuzat** [comment] 2024-02-09 18:19
@carlocaione, `NeoSolarized.nvim` does not support `fidget`. 
`NvimTree` does have hightlighted cursor line (see sreenshots)
![Screenshot 2024-02-09 234448](https://github.com/Tsuzat/NeoSolarized.nvim/assets/70003855/8b266a12-aefc-4d22-b590-84b5eb188c02)
![Screenshot 2024-02-09 234525](https://github.com/Tsuzat/NeoSolarized.nvim/assets/70003855/5caa5e2b-e61c-4e84-afcb-dc60df2a1326)

Try checking the config and highlights of `NeoTree`. Hope you find the solution. Happy Coding ❤️

**Comment by Tsuzat** [comment] 2024-02-25 08:57
Hope the issue is resolved. I'm closing this issue. You can reopen it if you have any issue(s). Happy Coding :)

**Closed as completed by Tsuzat** 2024-02-25 08:57 UTC
